#!/bin/sh

NGINX_PATH="/usr/local/nginx"

if [ -f $NGINX_PATH/logs/nginx.pid ]; then
    $NGINX_PATH/sbin/nginx -s quit
    rm -f $NGINX_PATH/logs/nginx.pid
fi

$NGINX_PATH/sbin/nginx -g "daemon off;"
